name = "solarized-fp"
version = "0.0.2"
authors = ["JayTr <netlambda@gmail.com>"]
description = "JayTr's solarized-fp Themes"
repository = "https://github.com/lohazo/solarized-fp"
id = "solarized-fp"
schema_version = 1
