name = "solarized-fp"
version = "0.0.2"
authors = ["JayTr"]
description = "Based on Solarized light and tailored for functional programming style."
repository = "https://github.com/lohazo/solarized-fp"
id = "solarized-fp"
schema_version = 1